services:
  app:
    image: isaaclb98/imgtour:latest
    ports:
      - "8000:8000"
    volumes:
      - imgtour_data:/data
      - /path/to/images:/images:ro
      - imgtour_export:/export:rw
    environment:
      - IMAGE_FOLDERS=/images
      - EXPORT_FOLDER=/export
      - SAMPLE_SIZE=0
      - RESET=0
      - TOURNAMENT_MODE=normal
      # - TOURNAMENT_MODE=slow

volumes:
  imgtour_data:
  imgtour_export:
